// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/prawirdani/golang-restapi/internal/audit"
	mock "github.com/stretchr/testify/mock"
)

// NewRecorder creates a new instance of Recorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Recorder {
	mock := &Recorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Recorder is an autogenerated mock type for the Recorder type
type Recorder struct {
	mock.Mock
}

type Recorder_Expecter struct {
	mock *mock.Mock
}

func (_m *Recorder) EXPECT() *Recorder_Expecter {
	return &Recorder_Expecter{mock: &_m.Mock}
}

// Record provides a mock function for the type Recorder
func (_mock *Recorder) Record(ctx context.Context, e audit.Entry) error {
	ret := _mock.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, audit.Entry) error); ok {
		r0 = returnFunc(ctx, e)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Recorder_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type Recorder_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - ctx context.Context
//   - e audit.Entry
func (_e *Recorder_Expecter) Record(ctx any, e any) *Recorder_Record_Call {
	return &Recorder_Record_Call{Call: _e.mock.On("Record", ctx, e)}
}

func (_c *Recorder_Record_Call) Run(run func(ctx context.Context, e audit.Entry)) *Recorder_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 audit.Entry
		if args[1] != nil {
			arg1 = args[1].(audit.Entry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Recorder_Record_Call) Return(err error) *Recorder_Record_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Recorder_Record_Call) RunAndReturn(run func(ctx context.Context, e audit.Entry) error) *Recorder_Record_Call {
	_c.Call.Return(run)
	return _c
}
