// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/prawirdani/golang-restapi/internal/domain/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthRepository creates a new instance of AuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthRepository {
	mock := &AuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthRepository is an autogenerated mock type for the Repository type
type AuthRepository struct {
	mock.Mock
}

type AuthRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthRepository) EXPECT() *AuthRepository_Expecter {
	return &AuthRepository_Expecter{mock: &_m.Mock}
}

// GetResetPasswordToken provides a mock function for the type AuthRepository
func (_mock *AuthRepository) GetResetPasswordToken(ctx context.Context, value string) (*auth.ResetPasswordToken, error) {
	ret := _mock.Called(ctx, value)

	if len(ret) == 0 {
		panic("no return value specified for GetResetPasswordToken")
	}

	var r0 *auth.ResetPasswordToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*auth.ResetPasswordToken, error)); ok {
		return returnFunc(ctx, value)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *auth.ResetPasswordToken); ok {
		r0 = returnFunc(ctx, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.ResetPasswordToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, value)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthRepository_GetResetPasswordToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResetPasswordToken'
type AuthRepository_GetResetPasswordToken_Call struct {
	*mock.Call
}

// GetResetPasswordToken is a helper method to define mock.On call
//   - ctx context.Context
//   - value string
func (_e *AuthRepository_Expecter) GetResetPasswordToken(ctx interface{}, value interface{}) *AuthRepository_GetResetPasswordToken_Call {
	return &AuthRepository_GetResetPasswordToken_Call{Call: _e.mock.On("GetResetPasswordToken", ctx, value)}
}

func (_c *AuthRepository_GetResetPasswordToken_Call) Run(run func(ctx context.Context, value string)) *AuthRepository_GetResetPasswordToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthRepository_GetResetPasswordToken_Call) Return(resetPasswordToken *auth.ResetPasswordToken, err error) *AuthRepository_GetResetPasswordToken_Call {
	_c.Call.Return(resetPasswordToken, err)
	return _c
}

func (_c *AuthRepository_GetResetPasswordToken_Call) RunAndReturn(run func(ctx context.Context, value string) (*auth.ResetPasswordToken, error)) *AuthRepository_GetResetPasswordToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function for the type AuthRepository
func (_mock *AuthRepository) GetSession(ctx context.Context, sessionID string) (*auth.Session, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *auth.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*auth.Session, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *auth.Session); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthRepository_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type AuthRepository_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *AuthRepository_Expecter) GetSession(ctx interface{}, sessionID interface{}) *AuthRepository_GetSession_Call {
	return &AuthRepository_GetSession_Call{Call: _e.mock.On("GetSession", ctx, sessionID)}
}

func (_c *AuthRepository_GetSession_Call) Run(run func(ctx context.Context, sessionID string)) *AuthRepository_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthRepository_GetSession_Call) Return(session *auth.Session, err error) *AuthRepository_GetSession_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *AuthRepository_GetSession_Call) RunAndReturn(run func(ctx context.Context, sessionID string) (*auth.Session, error)) *AuthRepository_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// StoreResetPasswordToken provides a mock function for the type AuthRepository
func (_mock *AuthRepository) StoreResetPasswordToken(ctx context.Context, token *auth.ResetPasswordToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for StoreResetPasswordToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.ResetPasswordToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthRepository_StoreResetPasswordToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreResetPasswordToken'
type AuthRepository_StoreResetPasswordToken_Call struct {
	*mock.Call
}

// StoreResetPasswordToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token *auth.ResetPasswordToken
func (_e *AuthRepository_Expecter) StoreResetPasswordToken(ctx interface{}, token interface{}) *AuthRepository_StoreResetPasswordToken_Call {
	return &AuthRepository_StoreResetPasswordToken_Call{Call: _e.mock.On("StoreResetPasswordToken", ctx, token)}
}

func (_c *AuthRepository_StoreResetPasswordToken_Call) Run(run func(ctx context.Context, token *auth.ResetPasswordToken)) *AuthRepository_StoreResetPasswordToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.ResetPasswordToken
		if args[1] != nil {
			arg1 = args[1].(*auth.ResetPasswordToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthRepository_StoreResetPasswordToken_Call) Return(err error) *AuthRepository_StoreResetPasswordToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthRepository_StoreResetPasswordToken_Call) RunAndReturn(run func(ctx context.Context, token *auth.ResetPasswordToken) error) *AuthRepository_StoreResetPasswordToken_Call {
	_c.Call.Return(run)
	return _c
}

// StoreSession provides a mock function for the type AuthRepository
func (_mock *AuthRepository) StoreSession(ctx context.Context, session *auth.Session) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for StoreSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.Session) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthRepository_StoreSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreSession'
type AuthRepository_StoreSession_Call struct {
	*mock.Call
}

// StoreSession is a helper method to define mock.On call
//   - ctx context.Context
//   - session *auth.Session
func (_e *AuthRepository_Expecter) StoreSession(ctx interface{}, session interface{}) *AuthRepository_StoreSession_Call {
	return &AuthRepository_StoreSession_Call{Call: _e.mock.On("StoreSession", ctx, session)}
}

func (_c *AuthRepository_StoreSession_Call) Run(run func(ctx context.Context, session *auth.Session)) *AuthRepository_StoreSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.Session
		if args[1] != nil {
			arg1 = args[1].(*auth.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthRepository_StoreSession_Call) Return(err error) *AuthRepository_StoreSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthRepository_StoreSession_Call) RunAndReturn(run func(ctx context.Context, session *auth.Session) error) *AuthRepository_StoreSession_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateResetPasswordToken provides a mock function for the type AuthRepository
func (_mock *AuthRepository) UpdateResetPasswordToken(ctx context.Context, token *auth.ResetPasswordToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResetPasswordToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.ResetPasswordToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthRepository_UpdateResetPasswordToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResetPasswordToken'
type AuthRepository_UpdateResetPasswordToken_Call struct {
	*mock.Call
}

// UpdateResetPasswordToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token *auth.ResetPasswordToken
func (_e *AuthRepository_Expecter) UpdateResetPasswordToken(ctx interface{}, token interface{}) *AuthRepository_UpdateResetPasswordToken_Call {
	return &AuthRepository_UpdateResetPasswordToken_Call{Call: _e.mock.On("UpdateResetPasswordToken", ctx, token)}
}

func (_c *AuthRepository_UpdateResetPasswordToken_Call) Run(run func(ctx context.Context, token *auth.ResetPasswordToken)) *AuthRepository_UpdateResetPasswordToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.ResetPasswordToken
		if args[1] != nil {
			arg1 = args[1].(*auth.ResetPasswordToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthRepository_UpdateResetPasswordToken_Call) Return(err error) *AuthRepository_UpdateResetPasswordToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthRepository_UpdateResetPasswordToken_Call) RunAndReturn(run func(ctx context.Context, token *auth.ResetPasswordToken) error) *AuthRepository_UpdateResetPasswordToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSession provides a mock function for the type AuthRepository
func (_mock *AuthRepository) UpdateSession(ctx context.Context, session *auth.Session) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.Session) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthRepository_UpdateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSession'
type AuthRepository_UpdateSession_Call struct {
	*mock.Call
}

// UpdateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - session *auth.Session
func (_e *AuthRepository_Expecter) UpdateSession(ctx interface{}, session interface{}) *AuthRepository_UpdateSession_Call {
	return &AuthRepository_UpdateSession_Call{Call: _e.mock.On("UpdateSession", ctx, session)}
}

func (_c *AuthRepository_UpdateSession_Call) Run(run func(ctx context.Context, session *auth.Session)) *AuthRepository_UpdateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.Session
		if args[1] != nil {
			arg1 = args[1].(*auth.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthRepository_UpdateSession_Call) Return(err error) *AuthRepository_UpdateSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthRepository_UpdateSession_Call) RunAndReturn(run func(ctx context.Context, session *auth.Session) error) *AuthRepository_UpdateSession_Call {
	_c.Call.Return(run)
	return _c
}
