// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/prawirdani/golang-restapi/internal/domain/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthMessagePublisher creates a new instance of AuthMessagePublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthMessagePublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthMessagePublisher {
	mock := &AuthMessagePublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthMessagePublisher is an autogenerated mock type for the MessagePublisher type
type AuthMessagePublisher struct {
	mock.Mock
}

type AuthMessagePublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthMessagePublisher) EXPECT() *AuthMessagePublisher_Expecter {
	return &AuthMessagePublisher_Expecter{mock: &_m.Mock}
}

// SendResetPasswordEmail provides a mock function for the type AuthMessagePublisher
func (_mock *AuthMessagePublisher) SendResetPasswordEmail(ctx context.Context, msg auth.ResetPasswordEmailMessage) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for SendResetPasswordEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.ResetPasswordEmailMessage) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthMessagePublisher_SendResetPasswordEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendResetPasswordEmail'
type AuthMessagePublisher_SendResetPasswordEmail_Call struct {
	*mock.Call
}

// SendResetPasswordEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - msg auth.ResetPasswordEmailMessage
func (_e *AuthMessagePublisher_Expecter) SendResetPasswordEmail(ctx interface{}, msg interface{}) *AuthMessagePublisher_SendResetPasswordEmail_Call {
	return &AuthMessagePublisher_SendResetPasswordEmail_Call{Call: _e.mock.On("SendResetPasswordEmail", ctx, msg)}
}

func (_c *AuthMessagePublisher_SendResetPasswordEmail_Call) Run(run func(ctx context.Context, msg auth.ResetPasswordEmailMessage)) *AuthMessagePublisher_SendResetPasswordEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.ResetPasswordEmailMessage
		if args[1] != nil {
			arg1 = args[1].(auth.ResetPasswordEmailMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthMessagePublisher_SendResetPasswordEmail_Call) Return(err error) *AuthMessagePublisher_SendResetPasswordEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthMessagePublisher_SendResetPasswordEmail_Call) RunAndReturn(run func(ctx context.Context, msg auth.ResetPasswordEmailMessage) error) *AuthMessagePublisher_SendResetPasswordEmail_Call {
	_c.Call.Return(run)
	return _c
}
