// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// IsRevoked provides a mock function for the type Store
func (_mock *Store) IsRevoked(ctx context.Context, userID uuid.UUID, sessionID uuid.UUID, issuedAt time.Time) (bool, error) {
	ret := _mock.Called(ctx, userID, sessionID, issuedAt)

	if len(ret) == 0 {
		panic("no return value specified for IsRevoked")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time) (bool, error)); ok {
		return returnFunc(ctx, userID, sessionID, issuedAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time) bool); ok {
		r0 = returnFunc(ctx, userID, sessionID, issuedAt)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, sessionID, issuedAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Store_IsRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRevoked'
type Store_IsRevoked_Call struct {
	*mock.Call
}

// IsRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - sessionID uuid.UUID
//   - issuedAt time.Time
func (_e *Store_Expecter) IsRevoked(ctx any, userID any, sessionID any, issuedAt any) *Store_IsRevoked_Call {
	return &Store_IsRevoked_Call{Call: _e.mock.On("IsRevoked", ctx, userID, sessionID, issuedAt)}
}

func (_c *Store_IsRevoked_Call) Run(run func(ctx context.Context, userID uuid.UUID, sessionID uuid.UUID, issuedAt time.Time)) *Store_IsRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Store_IsRevoked_Call) Return(b bool, err error) *Store_IsRevoked_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Store_IsRevoked_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, sessionID uuid.UUID, issuedAt time.Time) (bool, error)) *Store_IsRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllForUser provides a mock function for the type Store
func (_mock *Store) RevokeAllForUser(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllForUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Store_RevokeAllForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllForUser'
type Store_RevokeAllForUser_Call struct {
	*mock.Call
}

// RevokeAllForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *Store_Expecter) RevokeAllForUser(ctx any, userID any) *Store_RevokeAllForUser_Call {
	return &Store_RevokeAllForUser_Call{Call: _e.mock.On("RevokeAllForUser", ctx, userID)}
}

func (_c *Store_RevokeAllForUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *Store_RevokeAllForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Store_RevokeAllForUser_Call) Return(err error) *Store_RevokeAllForUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Store_RevokeAllForUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *Store_RevokeAllForUser_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function for the type Store
func (_mock *Store) RevokeSession(ctx context.Context, sessionID uuid.UUID) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Store_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type Store_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *Store_Expecter) RevokeSession(ctx any, sessionID any) *Store_RevokeSession_Call {
	return &Store_RevokeSession_Call{Call: _e.mock.On("RevokeSession", ctx, sessionID)}
}

func (_c *Store_RevokeSession_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *Store_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Store_RevokeSession_Call) Return(err error) *Store_RevokeSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Store_RevokeSession_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID) error) *Store_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}
