// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewChecker creates a new instance of Checker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *Checker {
	mock := &Checker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Checker is an autogenerated mock type for the Checker type
type Checker struct {
	mock.Mock
}

type Checker_Expecter struct {
	mock *mock.Mock
}

func (_m *Checker) EXPECT() *Checker_Expecter {
	return &Checker_Expecter{mock: &_m.Mock}
}

// IsRevoked provides a mock function for the type Checker
func (_mock *Checker) IsRevoked(ctx context.Context, userID uuid.UUID, sessionID uuid.UUID, issuedAt time.Time) (bool, error) {
	ret := _mock.Called(ctx, userID, sessionID, issuedAt)

	if len(ret) == 0 {
		panic("no return value specified for IsRevoked")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time) (bool, error)); ok {
		return returnFunc(ctx, userID, sessionID, issuedAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time) bool); ok {
		r0 = returnFunc(ctx, userID, sessionID, issuedAt)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, sessionID, issuedAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Checker_IsRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRevoked'
type Checker_IsRevoked_Call struct {
	*mock.Call
}

// IsRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - sessionID uuid.UUID
//   - issuedAt time.Time
func (_e *Checker_Expecter) IsRevoked(ctx any, userID any, sessionID any, issuedAt any) *Checker_IsRevoked_Call {
	return &Checker_IsRevoked_Call{Call: _e.mock.On("IsRevoked", ctx, userID, sessionID, issuedAt)}
}

func (_c *Checker_IsRevoked_Call) Run(run func(ctx context.Context, userID uuid.UUID, sessionID uuid.UUID, issuedAt time.Time)) *Checker_IsRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Checker_IsRevoked_Call) Return(b bool, err error) *Checker_IsRevoked_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Checker_IsRevoked_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, sessionID uuid.UUID, issuedAt time.Time) (bool, error)) *Checker_IsRevoked_Call {
	_c.Call.Return(run)
	return _c
}
