// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewRevoker creates a new instance of Revoker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRevoker(t interface {
	mock.TestingT
	Cleanup(func())
}) *Revoker {
	mock := &Revoker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Revoker is an autogenerated mock type for the Revoker type
type Revoker struct {
	mock.Mock
}

type Revoker_Expecter struct {
	mock *mock.Mock
}

func (_m *Revoker) EXPECT() *Revoker_Expecter {
	return &Revoker_Expecter{mock: &_m.Mock}
}

// RevokeAllForUser provides a mock function for the type Revoker
func (_mock *Revoker) RevokeAllForUser(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllForUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Revoker_RevokeAllForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllForUser'
type Revoker_RevokeAllForUser_Call struct {
	*mock.Call
}

// RevokeAllForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *Revoker_Expecter) RevokeAllForUser(ctx any, userID any) *Revoker_RevokeAllForUser_Call {
	return &Revoker_RevokeAllForUser_Call{Call: _e.mock.On("RevokeAllForUser", ctx, userID)}
}

func (_c *Revoker_RevokeAllForUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *Revoker_RevokeAllForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Revoker_RevokeAllForUser_Call) Return(err error) *Revoker_RevokeAllForUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Revoker_RevokeAllForUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *Revoker_RevokeAllForUser_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function for the type Revoker
func (_mock *Revoker) RevokeSession(ctx context.Context, sessionID uuid.UUID) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Revoker_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type Revoker_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *Revoker_Expecter) RevokeSession(ctx any, sessionID any) *Revoker_RevokeSession_Call {
	return &Revoker_RevokeSession_Call{Call: _e.mock.On("RevokeSession", ctx, sessionID)}
}

func (_c *Revoker_RevokeSession_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *Revoker_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Revoker_RevokeSession_Call) Return(err error) *Revoker_RevokeSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Revoker_RevokeSession_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID) error) *Revoker_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}
