// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type Storage
func (_mock *Storage) Delete(ctx context.Context, path string) error {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Storage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Storage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *Storage_Expecter) Delete(ctx interface{}, path interface{}) *Storage_Delete_Call {
	return &Storage_Delete_Call{Call: _e.mock.On("Delete", ctx, path)}
}

func (_c *Storage_Delete_Call) Run(run func(ctx context.Context, path string)) *Storage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Storage_Delete_Call) Return(err error) *Storage_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Storage_Delete_Call) RunAndReturn(run func(ctx context.Context, path string) error) *Storage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Dir provides a mock function for the type Storage
func (_mock *Storage) Dir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Dir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Storage_Dir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dir'
type Storage_Dir_Call struct {
	*mock.Call
}

// Dir is a helper method to define mock.On call
func (_e *Storage_Expecter) Dir() *Storage_Dir_Call {
	return &Storage_Dir_Call{Call: _e.mock.On("Dir")}
}

func (_c *Storage_Dir_Call) Run(run func()) *Storage_Dir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Storage_Dir_Call) Return(s string) *Storage_Dir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Storage_Dir_Call) RunAndReturn(run func() string) *Storage_Dir_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type Storage
func (_mock *Storage) Exists(ctx context.Context, path string) (bool, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type Storage_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *Storage_Expecter) Exists(ctx interface{}, path interface{}) *Storage_Exists_Call {
	return &Storage_Exists_Call{Call: _e.mock.On("Exists", ctx, path)}
}

func (_c *Storage_Exists_Call) Run(run func(ctx context.Context, path string)) *Storage_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Storage_Exists_Call) Return(b bool, err error) *Storage_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Storage_Exists_Call) RunAndReturn(run func(ctx context.Context, path string) (bool, error)) *Storage_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type Storage
func (_mock *Storage) Get(ctx context.Context, path string) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Storage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *Storage_Expecter) Get(ctx interface{}, path interface{}) *Storage_Get_Call {
	return &Storage_Get_Call{Call: _e.mock.On("Get", ctx, path)}
}

func (_c *Storage_Get_Call) Run(run func(ctx context.Context, path string)) *Storage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Storage_Get_Call) Return(readCloser io.ReadCloser, err error) *Storage_Get_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *Storage_Get_Call) RunAndReturn(run func(ctx context.Context, path string) (io.ReadCloser, error)) *Storage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetURL provides a mock function for the type Storage
func (_mock *Storage) GetURL(ctx context.Context, path string, expiry time.Duration) (string, error) {
	ret := _mock.Called(ctx, path, expiry)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (string, error)); ok {
		return returnFunc(ctx, path, expiry)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) string); ok {
		r0 = returnFunc(ctx, path, expiry)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, path, expiry)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type Storage_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - expiry time.Duration
func (_e *Storage_Expecter) GetURL(ctx interface{}, path interface{}, expiry interface{}) *Storage_GetURL_Call {
	return &Storage_GetURL_Call{Call: _e.mock.On("GetURL", ctx, path, expiry)}
}

func (_c *Storage_GetURL_Call) Run(run func(ctx context.Context, path string, expiry time.Duration)) *Storage_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Storage_GetURL_Call) Return(s string, err error) *Storage_GetURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Storage_GetURL_Call) RunAndReturn(run func(ctx context.Context, path string, expiry time.Duration) (string, error)) *Storage_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type Storage
func (_mock *Storage) Put(ctx context.Context, path string, reader io.Reader, contentType string) error {
	ret := _mock.Called(ctx, path, reader, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, string) error); ok {
		r0 = returnFunc(ctx, path, reader, contentType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Storage_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type Storage_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - reader io.Reader
//   - contentType string
func (_e *Storage_Expecter) Put(ctx interface{}, path interface{}, reader interface{}, contentType interface{}) *Storage_Put_Call {
	return &Storage_Put_Call{Call: _e.mock.On("Put", ctx, path, reader, contentType)}
}

func (_c *Storage_Put_Call) Run(run func(ctx context.Context, path string, reader io.Reader, contentType string)) *Storage_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Storage_Put_Call) Return(err error) *Storage_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Storage_Put_Call) RunAndReturn(run func(ctx context.Context, path string, reader io.Reader, contentType string) error) *Storage_Put_Call {
	_c.Call.Return(run)
	return _c
}
