// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewFile creates a new instance of File. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *File {
	mock := &File{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// File is an autogenerated mock type for the File type
type File struct {
	mock.Mock
}

type File_Expecter struct {
	mock *mock.Mock
}

func (_m *File) EXPECT() *File_Expecter {
	return &File_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type File
func (_mock *File) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// File_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type File_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *File_Expecter) Close() *File_Close_Call {
	return &File_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *File_Close_Call) Run(run func()) *File_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *File_Close_Call) Return(err error) *File_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *File_Close_Call) RunAndReturn(run func() error) *File_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ContentType provides a mock function for the type File
func (_mock *File) ContentType() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ContentType")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// File_ContentType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContentType'
type File_ContentType_Call struct {
	*mock.Call
}

// ContentType is a helper method to define mock.On call
func (_e *File_Expecter) ContentType() *File_ContentType_Call {
	return &File_ContentType_Call{Call: _e.mock.On("ContentType")}
}

func (_c *File_ContentType_Call) Run(run func()) *File_ContentType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *File_ContentType_Call) Return(s string) *File_ContentType_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *File_ContentType_Call) RunAndReturn(run func() string) *File_ContentType_Call {
	_c.Call.Return(run)
	return _c
}

// Ext provides a mock function for the type File
func (_mock *File) Ext() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ext")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// File_Ext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ext'
type File_Ext_Call struct {
	*mock.Call
}

// Ext is a helper method to define mock.On call
func (_e *File_Expecter) Ext() *File_Ext_Call {
	return &File_Ext_Call{Call: _e.mock.On("Ext")}
}

func (_c *File_Ext_Call) Run(run func()) *File_Ext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *File_Ext_Call) Return(s string) *File_Ext_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *File_Ext_Call) RunAndReturn(run func() string) *File_Ext_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type File
func (_mock *File) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// File_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type File_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *File_Expecter) Name() *File_Name_Call {
	return &File_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *File_Name_Call) Run(run func()) *File_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *File_Name_Call) Return(s string) *File_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *File_Name_Call) RunAndReturn(run func() string) *File_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NoFile provides a mock function for the type File
func (_mock *File) NoFile() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NoFile")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// File_NoFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NoFile'
type File_NoFile_Call struct {
	*mock.Call
}

// NoFile is a helper method to define mock.On call
func (_e *File_Expecter) NoFile() *File_NoFile_Call {
	return &File_NoFile_Call{Call: _e.mock.On("NoFile")}
}

func (_c *File_NoFile_Call) Run(run func()) *File_NoFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *File_NoFile_Call) Return(b bool) *File_NoFile_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *File_NoFile_Call) RunAndReturn(run func() bool) *File_NoFile_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type File
func (_mock *File) Read(p []byte) (int, error) {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(p)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// File_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type File_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - p []byte
func (_e *File_Expecter) Read(p interface{}) *File_Read_Call {
	return &File_Read_Call{Call: _e.mock.On("Read", p)}
}

func (_c *File_Read_Call) Run(run func(p []byte)) *File_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *File_Read_Call) Return(n int, err error) *File_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *File_Read_Call) RunAndReturn(run func(p []byte) (int, error)) *File_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Seek provides a mock function for the type File
func (_mock *File) Seek(offset int64, whence int) (int64, error) {
	ret := _mock.Called(offset, whence)

	if len(ret) == 0 {
		panic("no return value specified for Seek")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, int) (int64, error)); ok {
		return returnFunc(offset, whence)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, int) int64); ok {
		r0 = returnFunc(offset, whence)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(int64, int) error); ok {
		r1 = returnFunc(offset, whence)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// File_Seek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seek'
type File_Seek_Call struct {
	*mock.Call
}

// Seek is a helper method to define mock.On call
//   - offset int64
//   - whence int
func (_e *File_Expecter) Seek(offset interface{}, whence interface{}) *File_Seek_Call {
	return &File_Seek_Call{Call: _e.mock.On("Seek", offset, whence)}
}

func (_c *File_Seek_Call) Run(run func(offset int64, whence int)) *File_Seek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *File_Seek_Call) Return(n int64, err error) *File_Seek_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *File_Seek_Call) RunAndReturn(run func(offset int64, whence int) (int64, error)) *File_Seek_Call {
	_c.Call.Return(run)
	return _c
}

// SetName provides a mock function for the type File
func (_mock *File) SetName(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for SetName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// File_SetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetName'
type File_SetName_Call struct {
	*mock.Call
}

// SetName is a helper method to define mock.On call
//   - name string
func (_e *File_Expecter) SetName(name interface{}) *File_SetName_Call {
	return &File_SetName_Call{Call: _e.mock.On("SetName", name)}
}

func (_c *File_SetName_Call) Run(run func(name string)) *File_SetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *File_SetName_Call) Return(err error) *File_SetName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *File_SetName_Call) RunAndReturn(run func(name string) error) *File_SetName_Call {
	_c.Call.Return(run)
	return _c
}
