// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/prawirdani/golang-restapi/internal/ports/throttle"
	mock "github.com/stretchr/testify/mock"
)

// NewThrottler creates a new instance of Throttler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewThrottler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Throttler {
	mock := &Throttler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Throttler is an autogenerated mock type for the Throttler type
type Throttler struct {
	mock.Mock
}

type Throttler_Expecter struct {
	mock *mock.Mock
}

func (_m *Throttler) EXPECT() *Throttler_Expecter {
	return &Throttler_Expecter{mock: &_m.Mock}
}

// Release provides a mock function for the type Throttler
func (_mock *Throttler) Release(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Throttler_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type Throttler_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *Throttler_Expecter) Release(ctx any, key any) *Throttler_Release_Call {
	return &Throttler_Release_Call{Call: _e.mock.On("Release", ctx, key)}
}

func (_c *Throttler_Release_Call) Run(run func(ctx context.Context, key string)) *Throttler_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Throttler_Release_Call) Return(err error) *Throttler_Release_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Throttler_Release_Call) RunAndReturn(run func(ctx context.Context, key string) error) *Throttler_Release_Call {
	_c.Call.Return(run)
	return _c
}

// TryAcquire provides a mock function for the type Throttler
func (_mock *Throttler) TryAcquire(ctx context.Context, key string, ttl time.Duration) (throttle.Result, error) {
	ret := _mock.Called(ctx, key, ttl)

	if len(ret) == 0 {
		panic("no return value specified for TryAcquire")
	}

	var r0 throttle.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (throttle.Result, error)); ok {
		return returnFunc(ctx, key, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) throttle.Result); ok {
		r0 = returnFunc(ctx, key, ttl)
	} else {
		r0 = ret.Get(0).(throttle.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, key, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Throttler_TryAcquire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryAcquire'
type Throttler_TryAcquire_Call struct {
	*mock.Call
}

// TryAcquire is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - ttl time.Duration
func (_e *Throttler_Expecter) TryAcquire(ctx any, key any, ttl any) *Throttler_TryAcquire_Call {
	return &Throttler_TryAcquire_Call{Call: _e.mock.On("TryAcquire", ctx, key, ttl)}
}

func (_c *Throttler_TryAcquire_Call) Run(run func(ctx context.Context, key string, ttl time.Duration)) *Throttler_TryAcquire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Throttler_TryAcquire_Call) Return(result throttle.Result, err error) *Throttler_TryAcquire_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *Throttler_TryAcquire_Call) RunAndReturn(run func(ctx context.Context, key string, ttl time.Duration) (throttle.Result, error)) *Throttler_TryAcquire_Call {
	_c.Call.Return(run)
	return _c
}
