services:
  app:
    build: 
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    ports:
      - 42069:42069 # Service port
    volumes:
      - ./logs:/app/logs
    # For Linux, to access host machine from container
    extra_hosts: 
      - "host.docker.internal:host-gateway"

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./config/grafana:/etc/grafana/provisioning
      - grafana:/var/lib/grafana

volumes:
  grafana:
