-- +goose Up
-- +goose StatementBegin
CREATE TABLE audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id UUID REFERENCES users (id) ON DELETE SET NULL,
  action VARCHAR(100) NOT NULL,
  entity VARCHAR(50) NOT NULL,
  entity_id VARCHAR(100) NOT NULL,
  prev JSONB,
  next JSONB,
  meta JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW ()
);

CREATE INDEX audit_logs_entity_idx ON audit_logs (entity, entity_id);

CREATE INDEX audit_logs_actor_idx ON audit_logs (actor_id);

CREATE INDEX audit_logs_created_at_idx ON audit_logs (created_at DESC);

-- +goose StatementEnd
-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS audit_logs;

-- +goose StatementEnd
