// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewSessionRevoker creates a new instance of SessionRevoker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRevoker(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRevoker {
	mock := &SessionRevoker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionRevoker is an autogenerated mock type for the SessionRevoker type
type SessionRevoker struct {
	mock.Mock
}

type SessionRevoker_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRevoker) EXPECT() *SessionRevoker_Expecter {
	return &SessionRevoker_Expecter{mock: &_m.Mock}
}

// RevokeUserSessions provides a mock function for the type SessionRevoker
func (_mock *SessionRevoker) RevokeUserSessions(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeUserSessions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRevoker_RevokeUserSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeUserSessions'
type SessionRevoker_RevokeUserSessions_Call struct {
	*mock.Call
}

// RevokeUserSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *SessionRevoker_Expecter) RevokeUserSessions(ctx any, userID any) *SessionRevoker_RevokeUserSessions_Call {
	return &SessionRevoker_RevokeUserSessions_Call{Call: _e.mock.On("RevokeUserSessions", ctx, userID)}
}

func (_c *SessionRevoker_RevokeUserSessions_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *SessionRevoker_RevokeUserSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRevoker_RevokeUserSessions_Call) Return(err error) *SessionRevoker_RevokeUserSessions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRevoker_RevokeUserSessions_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *SessionRevoker_RevokeUserSessions_Call {
	_c.Call.Return(run)
	return _c
}
