{
 "title": "golang-restapi",
 "description": "Metrics for golang-restapi",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "App Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_info", "legendFormat": "{{ version }}" }
   ]
  },
  {
   "title": "Environment",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_info", "legendFormat": "{{environment}}" }
   ]
  },
  {
   "title": "AVG Handler Response Time",
   "type": "stat",
   "description": "Reflects the time taken for the handler function to execute and respond.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(app_request_duration_sum[5m])) / sum(rate(app_request_duration_count[5m])) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Request Over Time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(app_request_total[1m])) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(app_request_total{status_code=~\"4..|5..\"}[1m])) / sum(rate(app_request_total{}[1m])) * 100",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Error Request By Path",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(app_request_total{status_code=~\"4..|5..\"}[5m])) by (path)\n",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}