// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/prawirdani/golang-restapi/internal/domain/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewMailer creates a new instance of Mailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mailer {
	mock := &Mailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mailer is an autogenerated mock type for the Mailer type
type Mailer struct {
	mock.Mock
}

type Mailer_Expecter struct {
	mock *mock.Mock
}

func (_m *Mailer) EXPECT() *Mailer_Expecter {
	return &Mailer_Expecter{mock: &_m.Mock}
}

// PasswordRecovery provides a mock function for the type Mailer
func (_mock *Mailer) PasswordRecovery(ctx context.Context, msg auth.PasswordRecoveryMessage) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for PasswordRecovery")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.PasswordRecoveryMessage) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Mailer_PasswordRecovery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PasswordRecovery'
type Mailer_PasswordRecovery_Call struct {
	*mock.Call
}

// PasswordRecovery is a helper method to define mock.On call
//   - ctx context.Context
//   - msg auth.PasswordRecoveryMessage
func (_e *Mailer_Expecter) PasswordRecovery(ctx interface{}, msg interface{}) *Mailer_PasswordRecovery_Call {
	return &Mailer_PasswordRecovery_Call{Call: _e.mock.On("PasswordRecovery", ctx, msg)}
}

func (_c *Mailer_PasswordRecovery_Call) Run(run func(ctx context.Context, msg auth.PasswordRecoveryMessage)) *Mailer_PasswordRecovery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.PasswordRecoveryMessage
		if args[1] != nil {
			arg1 = args[1].(auth.PasswordRecoveryMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Mailer_PasswordRecovery_Call) Return(err error) *Mailer_PasswordRecovery_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Mailer_PasswordRecovery_Call) RunAndReturn(run func(ctx context.Context, msg auth.PasswordRecoveryMessage) error) *Mailer_PasswordRecovery_Call {
	_c.Call.Return(run)
	return _c
}
