// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/prawirdani/golang-restapi/internal/domain/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewMessagePublisher creates a new instance of MessagePublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessagePublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessagePublisher {
	mock := &MessagePublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MessagePublisher is an autogenerated mock type for the MessagePublisher type
type MessagePublisher struct {
	mock.Mock
}

type MessagePublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MessagePublisher) EXPECT() *MessagePublisher_Expecter {
	return &MessagePublisher_Expecter{mock: &_m.Mock}
}

// SendPasswordRecoveryEmail provides a mock function for the type MessagePublisher
func (_mock *MessagePublisher) SendPasswordRecoveryEmail(ctx context.Context, msg auth.PasswordRecoveryEmailMessage) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for SendPasswordRecoveryEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.PasswordRecoveryEmailMessage) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MessagePublisher_SendPasswordRecoveryEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPasswordRecoveryEmail'
type MessagePublisher_SendPasswordRecoveryEmail_Call struct {
	*mock.Call
}

// SendPasswordRecoveryEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - msg auth.PasswordRecoveryEmailMessage
func (_e *MessagePublisher_Expecter) SendPasswordRecoveryEmail(ctx interface{}, msg interface{}) *MessagePublisher_SendPasswordRecoveryEmail_Call {
	return &MessagePublisher_SendPasswordRecoveryEmail_Call{Call: _e.mock.On("SendPasswordRecoveryEmail", ctx, msg)}
}

func (_c *MessagePublisher_SendPasswordRecoveryEmail_Call) Run(run func(ctx context.Context, msg auth.PasswordRecoveryEmailMessage)) *MessagePublisher_SendPasswordRecoveryEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.PasswordRecoveryEmailMessage
		if args[1] != nil {
			arg1 = args[1].(auth.PasswordRecoveryEmailMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MessagePublisher_SendPasswordRecoveryEmail_Call) Return(err error) *MessagePublisher_SendPasswordRecoveryEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MessagePublisher_SendPasswordRecoveryEmail_Call) RunAndReturn(run func(ctx context.Context, msg auth.PasswordRecoveryEmailMessage) error) *MessagePublisher_SendPasswordRecoveryEmail_Call {
	_c.Call.Return(run)
	return _c
}
