// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/prawirdani/golang-restapi/internal/domain/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// GetPasswordRecoveryToken provides a mock function for the type Repository
func (_mock *Repository) GetPasswordRecoveryToken(ctx context.Context, tokenHash []byte) (*auth.PasswordRecoveryToken, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetPasswordRecoveryToken")
	}

	var r0 *auth.PasswordRecoveryToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (*auth.PasswordRecoveryToken, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) *auth.PasswordRecoveryToken); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.PasswordRecoveryToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_GetPasswordRecoveryToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPasswordRecoveryToken'
type Repository_GetPasswordRecoveryToken_Call struct {
	*mock.Call
}

// GetPasswordRecoveryToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash []byte
func (_e *Repository_Expecter) GetPasswordRecoveryToken(ctx interface{}, tokenHash interface{}) *Repository_GetPasswordRecoveryToken_Call {
	return &Repository_GetPasswordRecoveryToken_Call{Call: _e.mock.On("GetPasswordRecoveryToken", ctx, tokenHash)}
}

func (_c *Repository_GetPasswordRecoveryToken_Call) Run(run func(ctx context.Context, tokenHash []byte)) *Repository_GetPasswordRecoveryToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_GetPasswordRecoveryToken_Call) Return(passwordRecoveryToken *auth.PasswordRecoveryToken, err error) *Repository_GetPasswordRecoveryToken_Call {
	_c.Call.Return(passwordRecoveryToken, err)
	return _c
}

func (_c *Repository_GetPasswordRecoveryToken_Call) RunAndReturn(run func(ctx context.Context, tokenHash []byte) (*auth.PasswordRecoveryToken, error)) *Repository_GetPasswordRecoveryToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionByID provides a mock function for the type Repository
func (_mock *Repository) GetSessionByID(ctx context.Context, sessionID uuid.UUID) (*auth.Session, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByID")
	}

	var r0 *auth.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*auth.Session, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *auth.Session); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_GetSessionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionByID'
type Repository_GetSessionByID_Call struct {
	*mock.Call
}

// GetSessionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *Repository_Expecter) GetSessionByID(ctx interface{}, sessionID interface{}) *Repository_GetSessionByID_Call {
	return &Repository_GetSessionByID_Call{Call: _e.mock.On("GetSessionByID", ctx, sessionID)}
}

func (_c *Repository_GetSessionByID_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *Repository_GetSessionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_GetSessionByID_Call) Return(session *auth.Session, err error) *Repository_GetSessionByID_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *Repository_GetSessionByID_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID) (*auth.Session, error)) *Repository_GetSessionByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionByRefreshTokenHash provides a mock function for the type Repository
func (_mock *Repository) GetSessionByRefreshTokenHash(ctx context.Context, tokenHash []byte) (*auth.Session, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByRefreshTokenHash")
	}

	var r0 *auth.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (*auth.Session, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) *auth.Session); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_GetSessionByRefreshTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionByRefreshTokenHash'
type Repository_GetSessionByRefreshTokenHash_Call struct {
	*mock.Call
}

// GetSessionByRefreshTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash []byte
func (_e *Repository_Expecter) GetSessionByRefreshTokenHash(ctx interface{}, tokenHash interface{}) *Repository_GetSessionByRefreshTokenHash_Call {
	return &Repository_GetSessionByRefreshTokenHash_Call{Call: _e.mock.On("GetSessionByRefreshTokenHash", ctx, tokenHash)}
}

func (_c *Repository_GetSessionByRefreshTokenHash_Call) Run(run func(ctx context.Context, tokenHash []byte)) *Repository_GetSessionByRefreshTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_GetSessionByRefreshTokenHash_Call) Return(session *auth.Session, err error) *Repository_GetSessionByRefreshTokenHash_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *Repository_GetSessionByRefreshTokenHash_Call) RunAndReturn(run func(ctx context.Context, tokenHash []byte) (*auth.Session, error)) *Repository_GetSessionByRefreshTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// StorePasswordRecoveryToken provides a mock function for the type Repository
func (_mock *Repository) StorePasswordRecoveryToken(ctx context.Context, token *auth.PasswordRecoveryToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for StorePasswordRecoveryToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.PasswordRecoveryToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_StorePasswordRecoveryToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StorePasswordRecoveryToken'
type Repository_StorePasswordRecoveryToken_Call struct {
	*mock.Call
}

// StorePasswordRecoveryToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token *auth.PasswordRecoveryToken
func (_e *Repository_Expecter) StorePasswordRecoveryToken(ctx interface{}, token interface{}) *Repository_StorePasswordRecoveryToken_Call {
	return &Repository_StorePasswordRecoveryToken_Call{Call: _e.mock.On("StorePasswordRecoveryToken", ctx, token)}
}

func (_c *Repository_StorePasswordRecoveryToken_Call) Run(run func(ctx context.Context, token *auth.PasswordRecoveryToken)) *Repository_StorePasswordRecoveryToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.PasswordRecoveryToken
		if args[1] != nil {
			arg1 = args[1].(*auth.PasswordRecoveryToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_StorePasswordRecoveryToken_Call) Return(err error) *Repository_StorePasswordRecoveryToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_StorePasswordRecoveryToken_Call) RunAndReturn(run func(ctx context.Context, token *auth.PasswordRecoveryToken) error) *Repository_StorePasswordRecoveryToken_Call {
	_c.Call.Return(run)
	return _c
}

// StoreSession provides a mock function for the type Repository
func (_mock *Repository) StoreSession(ctx context.Context, session *auth.Session) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for StoreSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.Session) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_StoreSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreSession'
type Repository_StoreSession_Call struct {
	*mock.Call
}

// StoreSession is a helper method to define mock.On call
//   - ctx context.Context
//   - session *auth.Session
func (_e *Repository_Expecter) StoreSession(ctx interface{}, session interface{}) *Repository_StoreSession_Call {
	return &Repository_StoreSession_Call{Call: _e.mock.On("StoreSession", ctx, session)}
}

func (_c *Repository_StoreSession_Call) Run(run func(ctx context.Context, session *auth.Session)) *Repository_StoreSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.Session
		if args[1] != nil {
			arg1 = args[1].(*auth.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_StoreSession_Call) Return(err error) *Repository_StoreSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_StoreSession_Call) RunAndReturn(run func(ctx context.Context, session *auth.Session) error) *Repository_StoreSession_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePasswordRecoveryToken provides a mock function for the type Repository
func (_mock *Repository) UpdatePasswordRecoveryToken(ctx context.Context, token *auth.PasswordRecoveryToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePasswordRecoveryToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.PasswordRecoveryToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_UpdatePasswordRecoveryToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePasswordRecoveryToken'
type Repository_UpdatePasswordRecoveryToken_Call struct {
	*mock.Call
}

// UpdatePasswordRecoveryToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token *auth.PasswordRecoveryToken
func (_e *Repository_Expecter) UpdatePasswordRecoveryToken(ctx interface{}, token interface{}) *Repository_UpdatePasswordRecoveryToken_Call {
	return &Repository_UpdatePasswordRecoveryToken_Call{Call: _e.mock.On("UpdatePasswordRecoveryToken", ctx, token)}
}

func (_c *Repository_UpdatePasswordRecoveryToken_Call) Run(run func(ctx context.Context, token *auth.PasswordRecoveryToken)) *Repository_UpdatePasswordRecoveryToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.PasswordRecoveryToken
		if args[1] != nil {
			arg1 = args[1].(*auth.PasswordRecoveryToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_UpdatePasswordRecoveryToken_Call) Return(err error) *Repository_UpdatePasswordRecoveryToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_UpdatePasswordRecoveryToken_Call) RunAndReturn(run func(ctx context.Context, token *auth.PasswordRecoveryToken) error) *Repository_UpdatePasswordRecoveryToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSession provides a mock function for the type Repository
func (_mock *Repository) UpdateSession(ctx context.Context, session *auth.Session) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.Session) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_UpdateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSession'
type Repository_UpdateSession_Call struct {
	*mock.Call
}

// UpdateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - session *auth.Session
func (_e *Repository_Expecter) UpdateSession(ctx interface{}, session interface{}) *Repository_UpdateSession_Call {
	return &Repository_UpdateSession_Call{Call: _e.mock.On("UpdateSession", ctx, session)}
}

func (_c *Repository_UpdateSession_Call) Run(run func(ctx context.Context, session *auth.Session)) *Repository_UpdateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.Session
		if args[1] != nil {
			arg1 = args[1].(*auth.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_UpdateSession_Call) Return(err error) *Repository_UpdateSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_UpdateSession_Call) RunAndReturn(run func(ctx context.Context, session *auth.Session) error) *Repository_UpdateSession_Call {
	_c.Call.Return(run)
	return _c
}
