app:
  Name: golang-restapi
  Version: 1.0.0
  Port: 42069 
  Environment: DEV

db:
  Username: postgres
  Password: 
  Host: localhost
  Port: 5432
  Name: db-name 
  MinConns: 1
  MaxConns: 5
  MaxConnLifetime: 60 # In Minute

cors:
  Origins: localhost:3000 # Comma separated list of origins
  Credentials: true

token:
  SecretKey: secret
  AccessTokenExpiry: 15 # In Minutes
  RefreshTokenExpiry: 7 # In Days
