global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'golang-restapi'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:42070'] # host:port of the metrics server, the port is +1 of the app server port
