apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    orgId: 1
    uid: prometheus-ds
    url: http://prometheus:9090
    editable: true

  - name: Loki
    type: loki
    orgId: 1
    uid: loki-ds
    url: http://loki:3100
    editable: true
