package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/prawirdani/golang-restapi/config"
	"github.com/prawirdani/golang-restapi/internal/audit"
	"github.com/prawirdani/golang-restapi/internal/auth"
	"github.com/prawirdani/golang-restapi/internal/rbac"
	"github.com/prawirdani/golang-restapi/internal/user"
)

const permissionsCmdName = "permissions"

var permissionsCmd = command{
	name:    permissionsCmdName,
	summary: "dump registered permission codes as a JavaScript array",
	run:     runPermissions,
}

// runPermissions prints every permission code registered by the domain
// services. It is authoritative: rather than grepping for constants, it
// replays the same RegisterPermissions calls the services make at startup.
func runPermissions(args []string) error {
	fs := flag.NewFlagSet(permissionsCmdName, flag.ContinueOnError)
	out := fs.String("out", "", "write to this file instead of stdout")
	if err := fs.Parse(args); err != nil {
		return err
	}

	perms := gatherPermissions()

	var b strings.Builder
	b.WriteString("// Code generated by cli permissions; DO NOT EDIT.\n")
	b.WriteString("// Every permission code the server registers via rbac.RegisterPermissions.\n")
	b.WriteString("export const PERMISSIONS = [\n")
	for _, p := range perms {
		fmt.Fprintf(&b, "  %q,\n", p)
	}
	b.WriteString("];\n")

	if *out == "" {
		fmt.Print(b.String())
		return nil
	}

	if err := os.WriteFile(*out, []byte(b.String()), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", *out, err)
	}
	fmt.Fprintf(os.Stderr, "wrote %d permissions to %s\n", len(perms), *out)

	return nil
}

// gatherPermissions replays the service constructors to collect the
// registered permissions, returning a unique, sorted list.
func gatherPermissions() []string {
	authorizer := rbac.NewAuthorizer()

	// Constructors only store their dependencies and call RegisterPermissions,
	// so nil dependencies are safe here. Keep this in sync with the services
	// wired in cmd/api/container.go — a new domain that registers permissions
	// must be replayed here too.
	user.NewService(nil, nil, nil, authorizer, nil)
	audit.NewAuditService(authorizer, nil)
	auth.NewService(&config.Config{}, nil, nil, nil, authorizer, nil, nil, nil)

	seen := make(map[string]struct{})
	for _, perms := range authorizer.Permissions() {
		for perm := range perms {
			seen[string(perm)] = struct{}{}
		}
	}

	list := make([]string, 0, len(seen))
	for perm := range seen {
		list = append(list, perm)
	}
	sort.Strings(list)

	return list
}
